[package]
name = "osrs-rtge"
version = "0.1.5"
edition = "2021"

[dependencies]
ureq = {version="2.10.0",features = ["json"]}
serde = {version="1.0.204", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
mockito = "1.4.0"
